I18n.en =
  menu:
    schema: "スキーマ"
    new: "新規 ..."
    load: "開く ..."
    save: "保存"
    save_as: "名前をつけて保存 ..."
    templates: "テンプレート ..."
    properties: "プロパティ ..."
    share: "共有 ..."
    import: "インポート ..."
    edit: "編集"
    undo: "元に戻す"
    redo: "やり直す"
    select_all: "全て選択"
    select_none: "選択解除"
    delete_selected: "選択中を削除"
    insert: "挿入"
    table: "テーブル"
    note: "メモ"
    view: "表示"
    show_minimap: "ミニマップを表示"
    hide_minimap: "ミニマップを非表示"
    show_sidebar: "サイドバーを表示"
    hide_sidebar: "サイドバーを非表示"
    show_grid: "グリッドを表示"
    hide_grid: "グリッドを非表示"
    sort_items: "アイテムをソート"
    linetype: "線タイプ"
    bezier: "ベジエ曲線"
    cornered: "角直線"
    options: "オプション ..."
    export: "エクスポート"
    sql: "SQL ..."
    image: "画像 ..."
    help: "ヘルプ"
    index: "インデックス"
    changes: "変更履歴"
    shortcuts: "ショートカットキー"
    feedback: "フィードバック"
    about: "アプリについて"
    guest: "ゲスト"
    login: "ログイン"
    logout: "ログアウト"
    settings: "設定"
  panel:
    history: "履歴"
    last_versions_label: "このスキーマの過去10バージョン:"
    properties: "プロパティ"
    properties_schema_name: "スキーマ名:"
    properties_database: "データベース:"
    comments: "コメント"
    comment_placeholder: "ここにコメントを入力"
    send: "送信"
  dialog:
    new_schema: "New Schema"
    new_schema_title: "Title"
    new_schema_database: "Database"
    new_schema_type_info: """Selecting the "generic" database type will allow you to generate SQL for all the databases; but you will only have access to the generic datatypes."""
    new_schema_create_new: "Create New Schema"
    load_schema: "Load Schema"
    load_schema_your_schemas: "Your Schemas:"
    load_schema_schema_name: "Schema Name"
    load_schema_database: "Database"
    load_schema_last_save: "Last Save"
    load_schema_shared_with_you: "Schemas shared with you:"
    load_schema_owner: "Owner"
    load_schema_no_schemas: "You haven't saved any schemas"
    load_schema_no_shared_schemas: "There are no schemas shared with you"
    saveas: "Save As"
    saveas_title: "Title"
    saveas_button: "Save As"
    templates: "Templates"
    templates_schema_name: "Schema Name"
    templates_database: "Database"
    templates_description: "Description"
    properties: "Schema Properties"
    properties_title: "Title"
    properties_publish: "Publish as template"
    properties_template_info: "(Templates are visible to every user)"
    properties_delete_schema: "Delete Schema"
    properties_delete_alert: "(You will permanently delete this schema and all associated comments)"
    properties_save: "Save Changes"
    share: "Share"
    share_info: "You can share your schema with up to 5 users"
    share_email: "E-mail"
    share_access: "Access"
    share_read_only: "Read only"
    share_read_write: "Read and write"
    share_send_email: "Send invitation e-mail"
    share_invite_button: "Invite"
    share_collaborators: "Collaborators:"
    import: "Import Sql"
    login_email: "E-mail"
    login_password: "Password"
    login_button: "Login"
    login_forgot_password: "I forgot my password"
    options: "Options"
    options_line_colors: "Line Colors"
    options_invert_line_direction: "Invert line direction"
    options_show_fk_icon: "Show Foreign Key Icon"
    options_show_ai_icon: "Show Auto Increment Icon"
    options_show_not_null_icon: "Show Not Null icon"
    options_show_default_values: "Show Default Values"
    options_language: "Language"
    options_save_changes: "Save Changes"
    export_sql: "Export SQL"
    export_sql_generate: "Generate SQL"
    export_sql_download: "Download SQL file"
    export_image: "Export Image"
    export_image_zoomin: "Zoom in"
    export_image_zoomout: "Zoom out"
    export_image_reset: "Reset"
    export_image_open_in_new_tab: "Open image in new tab"
    help: "Help"
    shortcuts: "Keyboard Shortcuts"
    help_changelog: "Changes"
    feedback: "Feedback"
    feedback_type: "Feedback Type"
    feedback_bug: "Bug report"
    feedback_feature: "Feature Request"
    feedback_help: "Help"
    feedback_other: "Other"
    feedback_message: "Message"
    feedback_button: "Send Feedback"
    about: "About dbdesigner.net"
    user_settings: "User Settings"
    user_settings_username: "Username"
    user_settings_email: "E-mail"
    user_settings_save: "Save Changes"
    login: "Login"
    close: "Close"
    back: "Back"
    dirty_schema_confirmation: "Unsaved changes!"
    dirty_schema_confirmation_message: "You have unsaved changes in your schema, would you like to save it?"
    dirty_schema_confirmation_save_changes_button: "Save changes"
    dirty_schema_confirmation_discard_changes_and_continue_button: "Discard changes"
    dirty_schema_confirmation_cancel_button: "Cancel"
  designer:
    save_note_edit: "Save"
    cancel_note_edit: "Cancel"
    delete_note: "Delete"
    table_name: "Table Name"
    table_comment: "Table Comment"
    table_save: "Save"
    table_cancel: "Cancel"
    table_delete: "Delete Table"
    table_clone: "Clone Table"
    table_add_field: "Add field"
    field_name: "Name"
    field_type: "Type"
    field_size: "Size"
    field_default: "Default"
    field_unique: "Unique"
    field_allow_nulls: "Allow nulls"
    field_autoincrement: "Auto Increment"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Save"
    field_update: "Update"
    field_cancel: "Cancel"
    field_delete: "Delete Field"
    field_delete_alert: "Are you sure you want to delete this field?\n(hold shift to delete without confirmation)"
    field_ref_table: "Ref. Table"
    field_ref_field: "Ref. Field"
  alerts:
    delete_schema: "Are you sure you want to delete this schema?"
    server_error: "A server error occurred"
    schema_owner_error: "Only the schema owner can change share settings"
login_to_use_this_function: "You should login to use this function"
